name: deploy-container-images
on:
  workflow_dispatch:

jobs:
  deploy-singularity:
    runs-on: ubuntu-latest
    steps:
      - name: Singularity install with defaults
        uses: singularityhub/install-singularity@main
        with:
          singularity-version: '3.11.5'
      - name: Build Singularity library image
        shell: bash
        run: |
            sudo singularity build library.sif docker://ghcr.io/openms/openms-library:latest
      - name: Build Singularity tools image
        shell: bash
        run: |
            sudo singularity build executables.sif docker://ghcr.io/openms/openms-executables:latest
